GET http://localhost:3000
###
GET http://localhost:3000/songs
###
GET http://localhost:3000/songs/9
####
POST  http://localhost:3000/songs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwidXNlcklkIjoxLCJhcnRpc3RJZCI6MSwiaWF0IjoxNzEzMTA1MDI1LCJleHAiOjE3MTMxOTE0MjV9.unRo0_z05lH8D5MZJkTTsph4Fo65FW3QF8Ny6zhyycI

{
  "releasedDate": "2022-09-29",
  "duration": "02:34",
  "title": "song 11",
  "artists": [1,2],
  "lyrics": "abc"
}
###
PUT  http://localhost:3000/songs/12
Content-Type: application/json

{
  "releasedDate": "2022-09-29",
  "duration": "02:34",
  "title": "acb2222 update",
  "artists": ["hehehe udpate"],
  "lyrics": "heheheh update"
}

###
DELETE http://localhost:3000/songs/10



### Signup User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
"firstName": "Hari",
"lastName": "Le",
"email": "harile@gmail.com",
"password": "123456"
}

### Login User
POST http://localhost:3000/auth/login
Content-Type: application/json

{
"email": "john@gmail.com",
"password": "123456"
}

### Login User
POST http://localhost:3000/auth/login
Content-Type: application/json

{
"email": "harile@gmail.com",
"password": "123456"
}

###
GET http://localhost:3000/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik1lcmVkaXRoX01pbGxlcjEyQGhvdG1haWwuY29tIiwidXNlcklkIjoxOCwiaWF0IjoxNzEzNDMwNjc2LCJleHAiOjE3MTM1MTcwNzZ9.uXxwNKAtLlDA8TS927yh0UWQ1d7wrCBhoGJkcxxCoNs
#### enable 2fa
GET http://localhost:3000/auth/enable-2fa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhcmlsZUBnbWFpbC5jb20iLCJ1c2VySWQiOjIsImFydGlzdElkIjoyLCJpYXQiOjE3MTMyNDYzNDgsImV4cCI6MTcxMzMzMjc0OH0.d5sAeSjlYT1_D3LCzzfE4w4E4vkje39NI5LpTz_g71U

#### enable 2fa
GET http://localhost:3000/auth/disable-2fa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhcmlsZUBnbWFpbC5jb20iLCJ1c2VySWQiOjIsImFydGlzdElkIjoyLCJpYXQiOjE3MTMxOTI1ODcsImV4cCI6MTcxMzI3ODk4N30.h2rH8O1ZbTgRpYHcfDmWvd20_FllRwwRfiz9WszbHpk

### validate 2 fa
POST http://localhost:3000/auth/validate-2fa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhcmlsZUBnbWFpbC5jb20iLCJ1c2VySWQiOjIsImFydGlzdElkIjoyLCJpYXQiOjE3MTMyNDYzNDgsImV4cCI6MTcxMzMzMjc0OH0.d5sAeSjlYT1_D3LCzzfE4w4E4vkje39NI5LpTz_g71U

{
  "token": "005162"
}

### disable 2 fa
POST http://localhost:3000/auth/validate-2fa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhcmlsZUBnbWFpbC5jb20iLCJ1c2VySWQiOjIsImFydGlzdElkIjoyLCJpYXQiOjE3MTMxOTI1ODcsImV4cCI6MTcxMzI3ODk4N30.h2rH8O1ZbTgRpYHcfDmWvd20_FllRwwRfiz9WszbHpk

###
## API key: 7ea253ac-823e-427c-b513-8d5e0ac6b737
GET http://localhost:3000/auth/profile
Content-Type: application/json
Authorization: Bearer 7ea253ac-823e-427c-b513-8d5e0ac6b737

#### Test env
GET http://localhost:3000/auth/test